myprop.name=MySpring PROD

#log level : info
logging.level.com.rookies5.myspringbootlab=info

# mariadb db info
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

# hibernate info
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect