myprop.name=MySpring PROP

#log level : info
logging.level.com.basic.myspringboot=info

#mariadb
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

